---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-custom
# description will be included in the image's metadata
description: Custom image for my ASUS Vivobook based on Aurora-DX.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # Install some fonts, including Nerd Fonts and Google Fonts.
  - type: fonts
    fonts:
        nerd-fonts:
          - FiraCode # don't add spaces or "Nerd Font" suffix
          - Hack
          - SourceCodePro
          - Terminus
          - JetBrainsMono
          - NerdFontsSymbolsOnly
        google-fonts:
          - Roboto
          - Open Sans
          - Inter

  # Install ProtonVPN client with systemd offline mode to avoid failure during post installation
  - type: script
    scripts:
      - protonvpn.sh

  # Install default native packages for my workflow
  - type: dnf
    repos:
      cleanup: true
      nonfree: rpmfusion
    install:
      packages:
        - megasync
        - dolphin-megasync
        - https://bitwarden.com/download/?app=desktop&platform=linux&variant=rpm
  
  # Install default flatpak packages for my workflow
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          - com.discordapp.Discord

  - type: initramfs # this regenerates the initramfs to apply any changes made to the kernel modules or drivers
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
