---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-custom
# description will be included in the image's metadata
description: Custom image based on Bazzite with selected developer tools and personal customizations.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # 1. CONFIGURATION FILES

  # This copies lots of configuration files into the correct places
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /


  # 2. FONTS

  # Install some fonts, including Nerd Fonts and Google Fonts.
  - type: fonts
    fonts:
        nerd-fonts:
          - FiraCode # don't add spaces or "Nerd Font" suffix
          - Hack
          - SourceCodePro
          - Terminus
          - JetBrainsMono
          - NerdFontsSymbolsOnly
        google-fonts:
          - Roboto
          - Open Sans
          - Inter


  # 3. FINGERPRINT

  # Install custom fprinting shim for my ASUS Vivobook fingerprint reader
  - type: script
    scripts:
      - fingerprint.sh

  # Enable the custom resume service for the fingerprint reader to work after suspend
  - type: systemd
    system:
      enabled:
        - fprintd-resume.service


  # 4. APPLICATIONS

  # Install ProtonVPN client with systemd offline mode to avoid failure during post installation
  - type: script
    scripts:
      - protonvpn.sh

  # Install default native packages for my workflow (some packages might already be included in the base image)
  - type: dnf
    repos:
      cleanup: true
      files:
        - vscode.repo
        - https://download.opensuse.org/repositories/shells:zsh-users:zsh-completions/Fedora_Rawhide/shells:zsh-users:zsh-completions.repo
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      copr:
        - jdxcode/mise
        - atim/starship
      nonfree: rpmfusion
    install:
      packages:
        # Generic GUI applications
        - megasync
        - dolphin-megasync
        - https://bitwarden.com/download/?app=desktop&platform=linux&variant=rpm

        # Development tools
        - code
        - mise
        - podman-docker
        - git
        - git-lfs
        - git-delta
        - gh
        - cosign
        - gdb
        - strace
        - ltrace
        - btop
        - jq
        - tmux

        # Shell utilities
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - zsh-completions
        - starship
        - bat
        - zoxide
        - eza
        - fzf
        - ripgrep
        - fd-find

        # Other development stuff
        - gcc
        - gcc-c++
        - make
        - cmake
        - ninja-build
        - pkgconf-pkg-config
        - openssl-devel
        - libffi-devel
        - bzip2-devel
        - readline-devel
        - sqlite-devel
        - zlib-devel

  
  # Install default flatpak packages for my workflow
  - type: default-flatpaks
    configurations:
      - notify: false # avoids notification at every boot
        scope: user
        install:
          - com.discordapp.Discord

  - type: systemd
    user:
      enabled:
        # Enable the rootless podman socket for all users upon login
        - podman.socket


  # 5. FINALIZATION

  - type: initramfs # this regenerates the initramfs to apply any changes made to the kernel modules or drivers
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
