---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-custom
# description will be included in the image's metadata
description: Custom image based on Bazzite with selected developer tools and personal customizations.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # 1. CONFIGURATION FILES

  # This copies lots of configuration files into the correct places
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /


  # 2. FONTS

  # Install some fonts, including Nerd Fonts and Google Fonts.
  - type: fonts
    fonts:
        nerd-fonts:
          - FiraCode # don't add spaces or "Nerd Font" suffix
          - Hack
          - SourceCodePro
          - Terminus
          - JetBrainsMono
          - NerdFontsSymbolsOnly
        google-fonts:
          - Roboto
          - Open Sans
          - Inter


  # 3. FINGERPRINT

  # Install custom fprinting shim for my ASUS Vivobook fingerprint reader
  - type: script
    scripts:
      - fingerprint.sh

  # Enable the custom resume service for the fingerprint reader to work after suspend
  - type: systemd
    system:
      enabled:
        - fprintd-resume.service


  # 4. APPLICATIONS

  # Install ProtonVPN client with systemd offline mode to avoid failure during post installation
  - type: script
    scripts:
      - protonvpn.sh

  # Install default native packages for my workflow
  - type: dnf
    repos:
      cleanup: true
      files:
        - vscode.repo
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      copr:
        - jdxcode/mise
      nonfree: rpmfusion
    install:
      packages:
        - megasync
        - dolphin-megasync
        - https://bitwarden.com/download/?app=desktop&platform=linux&variant=rpm
        - code
        - mise
  
  # Install default flatpak packages for my workflow
  - type: default-flatpaks
    configurations:
      - notify: false # avoids notification at every boot
        scope: user
        install:
          - com.discordapp.Discord


  # 5. FINALIZATION

  - type: initramfs # this regenerates the initramfs to apply any changes made to the kernel modules or drivers
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
